### ISSUE TITLE
should images be parameters?

### ISSUE THREAD

**Issue by michelleN** [deislabs/cnab-spec#172] opened 2019-05-08 14:45 UTC
Right now, images (both OCI and VM) are specified in the `images` portion of the bundle.json file. See relevant portion of spec [here](https://github.com/deislabs/cnab-spec/blob/master/101-bundle-json.md#the-image-map). Should these images be moved into the `parameters` section which get passed in at runtime? Basically, is there a need to parameterized image information? or would that be going against the immutability attribute of a bundle?

also see: https://github.com/deislabs/cnab-spec/blob/6e4cac486d24e7ab78899845fa3e4e80f34c5d62/100-CNAB.md#summary

**Comment by jeremyrickard** [comment] 2019-05-08 16:05
My thought about this when it was discussed before was that this removes some of the immutability of the bundle. We'd be left with an immutable invocation image that has specific versions of tooling or config,  but the associated things that will actually end up running (i.e. the images) becomes a mutable thing. Although, providing these at runtime puts the burden of knowing what is what on the user so they should be aware of what will be installed and we would likely end up storing these in the claim so things could be reviewable and verifiable?

**Comment by michelleN** [comment] 2019-05-08 18:58
yes it would put more of the burden on the end user to use this overriding power wisely and yes we can put this info in the claim so that it's reviewable and verifiable.

I'm just thinking about the upgrade path out loud here. In Helm, you can override an image name/tag on an upgrade. This helps the user because they can keep all the Kubernetes configuration the same but just pass through a new image reference on upgrade. I'm wondering what the upgrade story looks like with bundles. Say I have a helm chart in my bundle that references an image and say the cnab `upgrade` action defined does a `helm upgrade --image <image>`. That image would need to be a parameter that gets passed in right now. 

There is value in having the images section which gives us the power of having an immutable bundle because you know exactly what is going to happen on `install` but maybe it is also okay to be able to pass in images as parameters for overriding in other actions like `upgrade`. It doesn't seem like anything special needs to happen in the spec for this to work today.

**Comment by youreddy** [comment] 2019-05-10 23:24
I'm trying to workout out how this would work with the introduction of bundle dependencies (PR https://github.com/deislabs/cnab-spec/pull/166). Let's say we have bundle A and it declares a dependency on a specific version of bundle B. If bundle B's images are mutable via parameters, that pretty much negates specifying a version in the first place and may cause unexpected behavior even when a dependent version is specified. 

`helm upgrade --image` is an interesting case. My opinion is that upgrading an installation's image should happen by specifying a new version of the bundle instead of through the `upgrade` action.

**Comment by GreenCee** [comment] 2019-05-11 19:54
One distinction is an image is expected to be an artifact (likely stored in a registry), and part of the manifest to export for a thick bundle.
Mutability may happen with relocation, but should maintain the same content hash.
Might be noting that a relocation should append and sign.

Parameters will often be mutable (though may have defaults), and I don't think them changing requires the same level of scrutiny as an image mutation.

**Comment by simonferquel** [comment] 2019-05-15 08:27
I think immutability is very important, but adding some kind of parameterization here could help for some scenarios.
One thing that we are evaluating for Docker-App that does not require any change from the spec, is to break the 1:1 relationship between component and images in the following way:
- add an image library (probably an images.yml) in the docker-app package sources
  - this would basically be a map `logical-name` -> `image reference` (or a receipe to build the image)
- services.yml `image` would then allow those 3 kinds of values:
  - a reference from a registry
  - a name present in the image library
  - a CNAB parameter with `allowed-values` being the set of images present in the image library

This way, we still have a finite set of component images to build the bundle, to guarantee its immutability, but allow some (somewhat limited) sort of parameterization.

**Comment by radu-matei** [comment] 2019-05-15 09:54
One thing to notice regarding mutability and relocation is that a relocation operation currently outputs a new bundle, so you don't actually change an existing bundle.

That being said, assuming we change one image in the bundle - how does this affect:

- checking of that specific image digest
- can you still trust the digest and signature of the bundle file itself?

> My opinion is that upgrading an installation's image should happen by specifying a new version of the bundle instead of through the upgrade action.

My initial instinct would be to agree with @youreddy's statement above.

**Comment by glyn** [comment] 2019-05-28 14:38
@michelleN I'd like to understand how upgrading a bundle is meant to happen in CNAB. Suppose the user has installed bundle B and then wants to upgrade to bundle B'. Do they simply use the runtime to execute the "upgrade" action of bundle B'?

If so, why does upgrade requires images to be parameterised since B' "knows" about the new images and can perform the corresponding upgrade (using helm or whatever)?

**Comment by simonferquel** [comment] 2019-06-06 16:47
One thing you can do, is introduce a new version of the bundle each time some images get updated (this way your whole CI/CD is assumed to have run and validated that the new images fit together correctly). You can upgrade an installation by referencing the new version of the bundle, thus upgrading the component images.

Also, one bundle author might prefer to treat some image names as parameter. The current spec completely allows that: you can just declare a string parameter and use it within the invocation image.

The current state of the spec satisfies both approaches, so I think we should keep as is. Wdyt?

**Comment by simonferquel** [comment] 2019-06-11 08:25
Should we close this issue, or should we add a non-normative section about image handling (like describing both approaches as valid, and listing pros and cons) ? cc @michelleN

**Comment by technosophos** [comment] 2019-07-15 21:26
It's been a month with no objection to closing this. So I am closing it.

**Closed by technosophos** 2019-07-15 21:26 UTC
